name: Go Lint code

on:
  push:
      branches:
          - master
          - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
          cache: false

      - name: Install and execute Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53.3