name: Go testing

on:
  push:
      branches:
          - master
          - main
  pull_request:

permissions:
  contents: read

jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
          - uses: actions/checkout@v3
          - name: Install Go
            uses: actions/setup-go@v4
            with:
                go-version: '1.20'

          - name: Test Go code
            run: go test ./...